global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Query;
global using Microsoft.Extensions.Logging;
global using PTM.Domain.CommunicationModels;
global using PTM.Domain.Entities.Interfaces;
global using System.Linq.Expressions;
global using Microsoft.Extensions.DependencyInjection;
global using PTM.Infrastructure.Data;
global using PTM.Domain.Entities;